import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { MobileSearchBarContextProvider } from "@/hooks/useMobileSearchBar";
import MobileSearchBar from "@/components/mobile-search-bar";
import { Toaster } from "@/components/ui/toaster";
import TanstackQueryClientProvider from "@/components/tanstack-query-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  creator: "Sanadh A N",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen antialiased bg-neutral-100 text-black dark:text-white dark:bg-black",
          inter.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryClientProvider>
            <MobileSearchBarContextProvider>
              <header className="relative z-10 bg-neutral-100 text-black dark:text-white dark:bg-black">
                <Navbar />
                <Sidebar />
              </header>
              <MobileSearchBar />
              <main>{children}</main>
              <Toaster />
            </MobileSearchBarContextProvider>
          </TanstackQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
