import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import React from "react";
export const metadata: Metadata = {
  title: "Movie Details",
  description: "Generated by create next app",
  creator: "Sanadh A N",
};

export default function Layout({ children }: PropsWithChildren) {
  return <main>{children}</main>;
}
